version: '3'
services:
  app:
    image: sarwar242/producthousebd:05
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_DATABASE: producthousebd
      DB_USERNAME: sarwar
      DB_PASSWORD: 123123
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: producthousebd
      MYSQL_USER: sarwar
      MYSQL_PASSWORD: 123123
      MYSQL_ROOT_PASSWORD: 123123
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
